"""adiciona_origem_viagem

Revision ID: 5bd8d6b462d7
Revises: fa40e1cbef9d
Create Date: 2026-04-11 19:32:33.714548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd8d6b462d7'
down_revision: Union[str, None] = 'fa40e1cbef9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Adiciona com server_default para não quebrar linhas existentes
    op.add_column('solicitacoes_viagem', sa.Column('origem', sa.String(length=200), nullable=False, server_default='São Paulo'))
    op.add_column('solicitacoes_viagem', sa.Column('iata_origem', sa.String(length=3), nullable=False, server_default='GRU'))
    # Remove server_default após preencher linhas existentes
    op.alter_column('solicitacoes_viagem', 'origem', server_default=None)
    op.alter_column('solicitacoes_viagem', 'iata_origem', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitacoes_viagem', 'iata_origem')
    op.drop_column('solicitacoes_viagem', 'origem')
    # ### end Alembic commands ###
