"""inicial

Revision ID: fa40e1cbef9d
Revises: 
Create Date: 2026-04-11 19:18:05.075160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = 'fa40e1cbef9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id', UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('solicitacoes_viagem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', UUID(as_uuid=True), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('iata_destino', sa.String(length=3), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('num_viajantes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'processando', 'concluido', 'falhou', name='statussolicitacao'), nullable=False),
    sa.Column('slug', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('logs_execucao_agente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('solicitacao_id', sa.Uuid(), nullable=False),
    sa.Column('agente', sa.Enum('voos', 'hoteis', 'atividades', 'arquiteto', name='nomeagente'), nullable=False),
    sa.Column('modelo_llm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('iniciado', 'concluido', 'falhou', name='statusexecucao'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=False),
    sa.Column('concluido_em', sa.DateTime(), nullable=True),
    sa.Column('duracao_segundos', sa.Float(), nullable=True),
    sa.Column('tokens_entrada_estimado', sa.Integer(), nullable=True),
    sa.Column('tokens_saida_estimado', sa.Integer(), nullable=True),
    sa.Column('custo_usd_estimado', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('entrada_resumo', sa.String(length=500), nullable=True),
    sa.Column('saida_resumo', sa.Text(), nullable=True),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('fonte_dados', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_viagem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roteiros',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('solicitacao_id', sa.Uuid(), nullable=False),
    sa.Column('nivel', sa.Enum('economico', 'conforto', 'premium', name='nivelroteiro'), nullable=False),
    sa.Column('custo_total_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes_viagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atividades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roteiro_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('custo_estimado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['roteiro_id'], ['roteiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospedagens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roteiro_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('preco_por_noite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('link_reserva', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['roteiro_id'], ['roteiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('roteiro_id', sa.Uuid(), nullable=False),
    sa.Column('companhia', sa.String(length=100), nullable=False),
    sa.Column('partida', sa.DateTime(), nullable=False),
    sa.Column('chegada', sa.DateTime(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('link_reserva', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['roteiro_id'], ['roteiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voos')
    op.drop_table('hospedagens')
    op.drop_table('atividades')
    op.drop_table('roteiros')
    op.drop_table('logs_execucao_agente')
    op.drop_table('solicitacoes_viagem')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
